/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f7f9fc",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#422000",
        "on-tertiary-fixed-variant": "#6e3900",
        "tertiary-fixed": "#ffdcc3",
        "surface-bright": "#f7f9fc",
        "secondary-fixed-dim": "#b8c8da",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#758dd5",
        "surface": "#f7f9fc",
        "error": "#ba1a1a",
        "primary": "#00113a",
        "on-secondary-fixed-variant": "#394857",
        "tertiary": "#240f00",
        "on-surface": "#191c1e",
        "surface-container-low": "#f2f4f7",
        "surface-container-high": "#e6e8eb",
        "on-secondary-fixed": "#0d1d2a",
        "secondary": "#50606f",
        "primary-fixed-dim": "#b3c5ff",
        "inverse-on-surface": "#eff1f4",
        "outline": "#757682",
        "on-surface-variant": "#444650",
        "on-tertiary": "#ffffff",
        "surface-container": "#eceef1",
        "secondary-container": "#d1e1f4",
        "on-primary-fixed": "#00174a",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb77d",
        "on-tertiary-container": "#d97600",
        "secondary-fixed": "#d4e4f6",
        "on-error": "#ffffff",
        "on-background": "#191c1e",
        "surface-container-highest": "#e0e3e6",
        "outline-variant": "#c5c6d2",
        "on-primary-fixed-variant": "#2a4386",
        "inverse-primary": "#b3c5ff",
        "surface-variant": "#e0e3e6",
        "on-secondary-container": "#556474",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "surface-dim": "#d8dadd",
        "surface-tint": "#435b9f",
        "on-tertiary-fixed": "#2f1500",
        "primary-container": "#002366"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
